<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <!-- Preserved for user-secrets (dotnet user-secrets list) -->
    <UserSecretsId>dotnet-Worker-7ba0af15-ce63-4a3a-828c-c48d250123e9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
