{
 "title": "BookStore — Fraude",
 "tags": [
  "bookstore",
  "fraud"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Decisões (5min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fraud_decisions_total[5m]))",
     "legendFormat": "Decisões"
    }
   ]
  },
  {
   "title": "Bloqueadas (5min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fraud_decisions_total{outcome=\"Rejected\"}[5m]))",
     "legendFormat": "Bloqueadas"
    }
   ]
  },
  {
   "title": "Em Revisão (5min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fraud_decisions_total{outcome=\"Review\"}[5m]))",
     "legendFormat": "Em Revisão"
    }
   ]
  },
  {
   "title": "Decisões por Resultado (5min)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(fraud_decisions_total[5m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Regras Mais Ativadas (5min)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum by (rule_code) (increase(fraud_rule_hits_total[5m])))",
     "legendFormat": "{{rule_code}}"
    }
   ]
  },
  {
   "title": "Latência de Decisão p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(fraud_decision_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Taxa de Decisões/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fraud_decisions_total[1m])) * 60",
     "legendFormat": "decisões/min"
    }
   ]
  }
 ]
}